# Generated by Django 4.2.1 on 2023-08-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'ELectronics'), ('Furniture', 'Furniture'), ('Home Appliances', 'Home Appliances'), ('Drugs', 'Drugs'), ('Tech', 'Tech'), ('Books', 'Books')], default='Electronics', max_length=20),
        ),
    ]
